version: "3.8"

services:

  devcontainer:
    image: ksjsms/bulnabi-humble-intel
    user: root
    privileged: true
    network_mode: host
    ipc: host
    environment:
      DISPLAY: ${DISPLAY}
      LIBGL_ALWAYS_INDIRECT: "0"
      NVIDIA_DRIVER_CAPABILITIES: all
      XDG_RUNTIME_DIR: /tmp
      MESA_LOADER_DRIVER_OVERRIDE: iris
      MESA_GL_VERSION_OVERRIDE: "4.6"
      MESA_GLSL_VERSION_OVERRIDE: "460"
    working_dir: /ros2_ws
    command: /bin/bash
    tty: true
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:cached
      - ../ros2_ws:/ros2_ws:cached
      - /home/ksj/PX4-Autopilot:/PX4-Autopilot:cached
      - vscode-extensions:/root/.vscode-server/extensions:cached
      - /dev/dri:/dev/dri
    devices:
      - /dev/dri:/dev/dri
      - /dev/dri/renderD128:/dev/dri/renderD128
      - /dev/dri/card0:/dev/dri/card0
    cap_add:
      - SYS_ADMIN
    security_opt:
      - seccomp:unconfined

  devcontainer_2:
    image: ksjsms/bulnabi-humble-intel
    user: root
    privileged: true
    network_mode: host
    ipc: host
    environment:
      DISPLAY: ${DISPLAY}
      LIBGL_ALWAYS_INDIRECT: "0"
      NVIDIA_DRIVER_CAPABILITIES: all
      XDG_RUNTIME_DIR: /tmp
      MESA_LOADER_DRIVER_OVERRIDE: iris
      MESA_GL_VERSION_OVERRIDE: "4.6"
      MESA_GLSL_VERSION_OVERRIDE: "460"
    working_dir: /ros2_ws
    command: /bin/bash
    tty: true
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:cached
      - ../ros2_ws:/ros2_ws:cached
      - ../PX4-Autopilot:/home/ksj/PX4-Autopilot:cached
      - /dev/dri:/dev/dri
    devices:
      - /dev/dri:/dev/dri
      - /dev/dri/renderD128:/dev/dri/renderD128
      - /dev/dri/card0:/dev/dri/card0
    cap_add:
      - SYS_ADMIN
    security_opt:
      - seccomp:unconfined

  devcontainer_3:
    image: ksjsms/bulnabi-humble-intel
    user: root
    privileged: true
    network_mode: host
    ipc: host
    environment:
      DISPLAY: ${DISPLAY}
      LIBGL_ALWAYS_INDIRECT: "0"
      NVIDIA_DRIVER_CAPABILITIES: all
      XDG_RUNTIME_DIR: /tmp
      MESA_LOADER_DRIVER_OVERRIDE: iris
      MESA_GL_VERSION_OVERRIDE: "4.6"
      MESA_GLSL_VERSION_OVERRIDE: "460"
    working_dir: /ros2_ws
    command: /bin/bash
    tty: true
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:cached
      - ../ros2_ws:/ros2_ws:cached
      - ../PX4-Autopilot:/home/ksj/PX4-Autopilot:cached
      - /dev/dri:/dev/dri
    devices:
      - /dev/dri:/dev/dri
      - /dev/dri/renderD128:/dev/dri/renderD128
      - /dev/dri/card0:/dev/dri/card0
    cap_add:
      - SYS_ADMIN
    security_opt:
      - seccomp:unconfined

volumes:
  vscode-extensions: